app:
  proj_title: thc.pm
  canonical_url: https://thc.pm
  jsonld_id: "A1QCnkf5yThfc6DLtFzs"
  gtm: W8J9GD7
  theme: vapor
  navbar_pages:
    Home: /
    Buy: /buy
    Sell: /sell
    Coins: /coins
    FAQs: /faqs
    News: /news
  social_media:
    #amazon: https://www.amazon.com/author/revmichaelhoyt
    #facebook: https://www.facebook.com/SaintsBeTold/
    #instagram: https://www.instagram.com/economyofdreams
    twitter: https://twitter.com/thcexchange
    linkedin: https://www.linkedin.com/in/economyofdreams
    youtube: https://youtube.com/channel/UCNx9OlImFLIp9zYI9xteX9g
    github: https://github.com/hoytnix/thc.pm
  contact:
    name: thc.pm
    phone: "+12698610617"
    email: "hello@thc.pm"
    mail:
      street: "1207 Delaware Ave #1337"
      city: Wilmington
      state: DE
      postal: "19806"
  coin_book:
    xmr: Monero
    btc: Bitcoin
    eth: Ethereum
    usdt: Tether
    doge: Dogecoin
    xrp: Ripple
    xlm: Lumens
    ada: Cardano
    sol: Solana
    matic: Polygon
    dot: Polkadot
    dai: Dai
    trx: TRON
    shib: Shiba Inu
    avax: Avalananche
    uni: Uniswap
    leo: UNUS SED LEO
    ltc: Litecoin
    maticmainnet: Polygon
    link: Chainlink
    etc: Ethereum Classic
    algo: Algorand
    bch: Bitcoin Cash
    xno: Nano
    vet: Vechain
    dash: DASH
    zec: Zcash
    usdt_omni: Tether (OMNI)
    usdterc20: Tether (ERC20)
    usdttrc20: Tether (TRC20)
    usdc: USD Coin
    busd: Binance USD
    usdp: Pax Dollar
    tusd: TrueUSD
    gusd: Gemini Dollar
    cake: PancakeSwap
    ust: TerraClassicUSD
  categories_book:
    Distillates & Isolates: ["Crude"]
    Flowers: ["Pre-Rolled", "Caviar", "Kief", "Biomass"]
    Hash: ["Hashish", "Moon Rocks", "Bubble Hash"]
    Edibles: ["Gummies", "Candies", "Chocolates", "Baked Goods", "Other"]
    Cartridges: ["510", "Pod", Disposable']
    Concentrates:
      [
        "Live Hash Rosin",
        "Flower Rosin (Cured)",
        "Flower Rosin (Fresh)",
        "Sugar Wax",
        "Crumble",
        "Budder",
        "Badder",
        "Shatter",
        "Ice Rocks",
      ]
    Digital Goods:
      [
        "1-To-1 Consulting",
        "1-To-Many Consulting",
        "Memberships",
        "File Downloads",
      ]
  tags_book:
    Manufacturing Process:
      [
        "cGMP",
        "USDA Organic",
        "Kosher",
        "Vegan",
        "Dairy-Free",
        "Sugar-Free",
        "Soy-Free",
      ]
    Flowers:
      [
        "Dry Sift",
        "Hand Trimmed",
        "Machine Trimmed",
        "Outdoor",
        "Indoor",
        "Hydroponic",
        "Aeroponic",
      ]
    Solvents: ["Solventless", "BHO", "CO2"]
    Pre-Packaged: ["Pre-Packaged w/ SKU", "Pre-Packaged w/o SKU"]
    Winterized: ["Is Winterized", "Not Winterized", "Partially Winterized"]
    Decarbed: ["Is Decarbed", "Not Decarbed", "Partially Decarbed"]
    Dewaxed: ["Is Dewaxed", "Not Dewaxed", "Partially Dewaxed"]
  cannabinoids_book:
    THC: ["Δ6a10a-THC", "Δ8-THC", "Δ9-THC", "Δ10-THC"]
    THC-A: ["Δ6a10a-THC-A", "Δ8-THC-A", "Δ9-THC-A", "Δ10-THC-A"]
    THC-O: ["Δ6a10a-THC-O", "Δ8-THC-O", "Δ9-THC-O", "Δ10-THC-O"]
    HHC: []
    HHC-O: []
    CBX: ["CBD", CBG', "CBN", "CBC", "CBT"]
    CBX-A: [CBD-A', "CBG-A", "CBN-A"]
    CBX-O: ["CBD-O", "CBG-O", "CBN-O"]
    Water Soluble:
      ["WS CBX", "WS CBX-O", "WS THC", "WS THC-O", "WS HHC", "WS HHC-O"]
    Other Acetates: []
    Other Cannabinoids:
      [
        "CBD-P",
        "THC-P",
        "THC-P-O",
        "HHC-P",
        "THC-JD",
        "CBD-V",
        "THC-V",
        "THC-H",
        "THC-B",
        "H4CBD",
        "JWH",
      ]
  countries_book:
    [
      "Worldwide",
      "North America",
      "South America",
      "Europe",
      "Africa",
      "Asia",
      "Asutralia",
    ]

blueprints:
  pages:
    - index:
        img: foobar.png
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - sign-up:
        title: Sign Up
        img: foobar.png
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - register:
        title: Register
        img: foobar.png
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - terms-of-use:
        title: Terms of Use
        description: Terms of Use
    - privacy-policy:
        title: Privacy Policy
        description: Privacy Policy
    - coins:
        title: Supported Coins
        description: Cryptocurrencies thc.pm Supports
    - sell:
        title: Sell
        description: Sell
    - buy:
        title: Buy
        description: Buy
  affiliates:
    - google:
        affiliate_url: "https://google.com"

models:
  news:
    templates:
      news: news
      articles: { title: article/* }
      tags: { tags: "tag/[*]" }
    items:
      hello-world:
        title: Hello World
        tags: [foo, bar, lorem, ipsum]
      foo:
        title: Foo
        tags: [foo, lorem]
      bar:
        title: Bar
        tags: [bar, ipsum]
  faqs:
    templates:
      faqs: faqs
      faq: { title: faq/* }
      tags: { tags: "tag/[*]" }
    items:
      payment-methods:
        title: Do You Accept Payments Other Than Crypto?
        tags: [buyers]
        short: <ul><li>While thc.pm does not escrow non-crypto payments some Sellers may accept payments other than Crypto such as Cash App, Venmo, Zelle, Credit Card & ACH.</li><li>You may filter by available payment methods from the <a href="/buy">search</a>.</li><li>thc.pm does not allow the public advertisement of contact information - <a href="#">PM</a> your favorite Seller to request their contact information if you choose to use an alternative payment method.</li><li>Again, thc.pm does not escrow non-crypto payments so use alternative payment methods at your own risk!</li><li>Also, you may not leave reviews or feedback for purchases made via alternative payment methods.</li><li>Purchases made via alternative payment methods may not be mentioned on thc.pm. Offenders will be temporarily banned from buying/selling for 15 days.</li></ul>
      instant-payments-101:
        title: How Do Instant Payments Work? [Instant Payments 101]
        tags: [instant payments, sellers, buyers]
        short: Instant Payments are powered by <a href="https://nowpayments.io">nowpayments.io</a>.<br/><br/>To enable Instant Payments for your Seller's account <a href="#">request Instant Payments permission</a>.
      escrow-101:
        title: How Does Escrow Work? [Escrow 101]
        tags: [escrow, sellers, buyers]
        short: Escrow is powered by <a href="https://nowpayments.io">nowpayments.io</a>.
      instant-payment-fees:
        title: What Are The Fees For Instant Payments?
        tags: [instant payments, buyers, sellers]
        short: 0.5% For Buyers & 1% For Sellers.
      escrow-fees:
        title: What Are The Fees For Escrow?
        tags: [escrow, buyers, sellers]
        short: 1% For Buyers & 2.5% For Sellers.
      sellers-bond:
        title: What's The Seller's Bond?
        tags: [sellers, bond]
        short: 1 $XMR (~$142 USD) Annually.
      sellers-bond-invitation-code:
        title: Do I have To Pay The Seller's Bond?
        tags: [sellers, bond, invitation code]
        short: No. You may have received an invitation code, if so, we waived your bond. Welcome aboard!<br/><br/>(Sellers with an invitation code have been pre-qualified as trusthworthy & ethical; and have Instant Payments automatically enabled for their accounts.)
