countries_book:
  Worldwide: []
  Africa:
    [
      Algeria,
      Angola,
      Benin,
      Botswana,
      Burkina Faso,
      Burundi,
      Cameroon,
      Cape Verde,
      Central African Republic,
      Chad,
      Comoros,
      Cote d’Ivoire,
      Democratic Republic of the Congo,
      Djibouti,
      Egypt,
      Equatorial Guinea,
      Eritrea,
      Eswatini,
      Ethiopia,
      Gabon,
      Ghana,
      Guinea,
      Guinea-Bissau,
      Kenya,
      Lesotho,
      Liberia,
      Libya,
      Madagascar,
      Malawi,
      Mali,
      Mauritania,
      Mayotte,
      Morocco,
      Mozambique,
      Namibia,
      Niger,
      Nigeria,
      Republic of the Congo,
      Rwanda,
      Saint Helena,
      Sao Tome and Principe,
      Senegal,
      Seychelles,
      Sierra Leone,
      Somalia,
      South Africa,
      South Sudan,
      Sudan,
      Tanzania,
      The Gambia,
      Togo,
      Tunisia,
      Uganda,
      Western Sahara,
      Zambia,
      Zimbabwe,
    ]
  Asia:
    [
      Afghanistan,
      Armenia,
      Azerbaijan,
      Bangladesh,
      Bhutan,
      Brunei,
      Burma (Myanmar),
      Cambodia,
      China,
      Christmas Island,
      Cocos (Keeling) Islands,
      Georgia,
      Hong Kong,
      India,
      Indonesia,
      Japan,
      Kazakhstan,
      North Korea,
      South Korea,
      Kyrgyzstan,
      Laos,
      Macau,
      Malaysia,
      Maldives,
      Mongolia,
      Nepal,
      Pakistan,
      Philippines,
      Russia,
      Singapore,
      Sri Lanka,
      Taiwan,
      Tajikistan,
      Thailand,
      Timor-Leste,
      Turkey,
      Turkmenistan,
      Uzbekistan,
      Vietnam,
    ]
  Europe:
    [
      Albania,
      Andorra,
      Austria,
      Belarus,
      Belgium,
      Bosnia and Herzegovina,
      Bulgaria,
      Croatia,
      Czech Republic,
      Denmark,
      EstoniaFaroe Islands,
      Finland,
      France,
      Germany,
      Gibraltar,
      Greece,
      Greenland,
      Guernsey,
      Holy See,
      Hungary,
      IcelandIreland,
      Italy,
      Jersey,
      Kosovo,
      Latvia,
      Liechtenstein,
      Lithuania,
      Luxembourg,
      Macedonia,
      Malta,
      Isle of ManMoldova,
      Monaco,
      Montenegro,
      Netherlands,
      Norway,
      Poland,
      Portugal,
      Romania,
      San Marino,
      Serbia,
      Slovakia / Slovenia,
      Spain,
      Sweden,
      Switzerland,
      Turkey,
      Ukraine,
      United Kingdom,
    ]
  North America: [Canada, Mexico, United States of America]
  Oceania:
    [
      American Samoa,
      Australia,
      Cook Islands,
      Coral Sea Islands,
      Fiji,
      French Polynesia,
      Guam,
      Kiribati,
      Marshall Islands,
      Micronesia,
      Nauru,
      New Caledonia,
      New Zealand,
      Niue,
      Norfolk Island,
      Northern Mariana Islands,
      Palau,
      Papua New Guinea,
      Pitcairn Islands,
      Samoa,
      Solomon Islands,
      Tokelau,
      Tonga,
      Tuvalu,
      Vanuatu,
      Wake Island,
      Wallis and Futuna,
    ]
  South America:
    [
      Argentina,
      Bolivia,
      Brazil,
      Chile,
      Colombia,
      Ecuador,
      Falkland Islands,
      French Guiana,
      Guyana,
      Paraguay,
      Peru,
      Suriname,
      Uruguay,
      Venezuela,
    ]
